github_token: ""
title: "Karoo Extensions"
max-releases: 3
output: output/index.html
repositories:
  - timklge/karoo-powerbar
  - timklge/karoo-reminder
  - timklge/karoo-headwind
  - maduwatas/Vin-HkE
  - lockevod/Karoo-KPower
  - lockevod/Karoo-KRemote
